# Generated by Django 5.1.4 on 2025-06-09 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 24, 5, 14, 31, 869577, tzinfo=datetime.timezone.utc)),
        ),
    ]
