# Generated by Django 5.1.4 on 2025-06-30 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 5, 4, 13, 401903, tzinfo=datetime.timezone.utc)),
        ),
    ]
