# Generated by Django 5.1.4 on 2025-06-11 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 26, 15, 13, 49, 63787, tzinfo=datetime.timezone.utc)),
        ),
    ]
