# Generated by Django 5.1.4 on 2025-06-30 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 15, 11, 18, 19, 320086, tzinfo=datetime.timezone.utc)),
        ),
    ]
