# Generated by Django 5.1.4 on 2025-07-01 03:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 3, 2, 49, 798665, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='PasswordResetOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
