# Generated by Django 5.1.4 on 2025-06-12 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_item_image_alter_item_end_time_itemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 6, 9, 51, 843948, tzinfo=datetime.timezone.utc)),
        ),
    ]
