# Generated by Django 5.1.4 on 2025-07-02 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 16, 19, 24, 626200, tzinfo=datetime.timezone.utc)),
        ),
    ]
