# Generated by Django 5.1.4 on 2025-06-23 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_item_category_item_tags_alter_item_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identification_image',
            field=models.ImageField(blank=True, null=True, upload_to='identification_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='idetification_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 15, 24, 22, 60359, tzinfo=datetime.timezone.utc)),
        ),
    ]
