# Generated by Django 5.1.4 on 2025-07-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_email_alter_item_description_and_more'),
        ('myapp', '0006_alter_customuser_email_and_more'),
    ]

    operations = [
    ]
