# Generated by Django 5.1.4 on 2025-06-23 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_customuser_address_customuser_identification_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='idetification_number',
            new_name='identification_number',
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 15, 31, 22, 589275, tzinfo=datetime.timezone.utc)),
        ),
    ]
