# Generated by Django 5.1.4 on 2025-07-02 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('home_garden', 'Home & Garden'), ('collectibles', 'Collectibles & Art'), ('vehicles', 'Vehicles & Parts')], default='electronics', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 16, 22, 9, 847860, tzinfo=datetime.timezone.utc)),
        ),
    ]
