# Generated by Django 5.1.4 on 2025-07-02 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_item_category_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 16, 27, 39, 146413, tzinfo=datetime.timezone.utc)),
        ),
    ]
