# Generated by Django 5.1.4 on 2025-07-02 17:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('bid', 'Bid Related'), ('auction_won', 'Auction Won'), ('auction_lost', 'Auction Lost'), ('item_sold', 'Item Sold'), ('payment', 'Payment'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('home_garden', 'Home & Garden'), ('collectibles', 'Collectibles & Art'), ('vehicles', 'Vehicles & Parts'), ('books', 'Books & Stationery'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('health_beauty', 'Health & Beauty'), ('jewelry', 'Jewelry & Accessories'), ('music_movies', 'Music & Movies'), ('pet_supplies', 'Pet Supplies'), ('tools_home_improvement', 'Tools & Home Improvement'), ('baby_products', 'Baby Products'), ('other', 'Other')], default='electronics', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 17, 1, 10, 337051, tzinfo=datetime.timezone.utc)),
        ),
    ]
