# Generated by Django 5.1.4 on 2025-06-23 16:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_customuser_profile_picture_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 8, 16, 12, 26, 361194, tzinfo=datetime.timezone.utc)),
        ),
    ]
