# Generated by Django 5.1.4 on 2025-07-02 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 17, 17, 18, 40, 594508, tzinfo=datetime.timezone.utc)),
        ),
    ]
