# Generated by Django 5.1.4 on 2025-07-03 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 5, 46, 21, 48458, tzinfo=datetime.timezone.utc)),
        ),
    ]
