# Generated by Django 5.1.4 on 2025-06-24 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_item_end_time_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='identification_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/identification_images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 9, 13, 18, 32, 79889, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
