# Generated by Django 5.1.4 on 2025-07-03 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 18, 8, 23, 13, 100165, tzinfo=datetime.timezone.utc)),
        ),
    ]
