# Generated by Django 5.1.4 on 2025-06-25 13:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_customuser_identification_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter a valid Nepal mobile number with or without +977.', max_length=13, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid Nepal mobile number like '+97798XXXXXXXX' or '98XXXXXXXX'.", regex='^(\\+977)?9\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 10, 13, 34, 33, 831677, tzinfo=datetime.timezone.utc)),
        ),
    ]
