# Generated by Django 5.1.4 on 2025-07-19 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 7, 22, 42, 110002, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('bid', 'Bid Related'), ('auction_won', 'Auction Won'), ('auction_lost', 'Auction Lost'), ('item_sold', 'Item Sold'), ('payment', 'Payment'), ('payment_received', 'Payment Received'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
