# Generated by Django 5.1.4 on 2025-07-19 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_item_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 7, 30, 31, 584672, tzinfo=datetime.timezone.utc)),
        ),
    ]
