# Generated by Django 5.1.4 on 2025-07-19 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20250719_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 15, 13, 10, 717644, tzinfo=datetime.timezone.utc)),
        ),
    ]
