# Generated by Django 5.1.4 on 2025-07-19 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing & Fashion'), ('home_garden', 'Home & Garden'), ('collectibles', 'Collectibles & Art'), ('vehicles', 'Vehicles & Parts'), ('books', 'Books & Stationery'), ('sports', 'Sports & Outdoors'), ('toys', 'Toys & Games'), ('health_beauty', 'Health & Beauty'), ('jewelry', 'Jewelry & Accessories'), ('music_movies', 'Music & Movies'), ('pet_supplies', 'Pet Supplies'), ('tools_home_improvement', 'Tools & Home Improvement'), ('baby_products', 'Baby Products'), ('other', 'Other')], default='AllCategories', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 3, 19, 30, 51, 495446, tzinfo=datetime.timezone.utc)),
        ),
    ]
