# Generated by Django 5.1.4 on 2025-07-20 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_item_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 4, 4, 21, 29, 207196, tzinfo=datetime.timezone.utc)),
        ),
    ]
